
language: java

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - mvn clean package

after_script:
  - docker build -t billryan/kafka-connect:${TRAVIS_COMMIT} .
  - docker tag billryan/kafka-connect:${TRAVIS_COMMIT} billryan/kafka-connect:latest
  - docker push billryan/kafka-connect:${TRAVIS_COMMIT}
  - docker push billryan/kafka-connect:latest
